### ISSUE TITLE
Useless use of linux command

### ISSUE THREAD

**Issue by bioinfornatics** [RRZE-HPC/pylikwid#11]
Currently, the setup use linux command such as `find` this could be written in pure python using:
- os.walk
- glob.iglob

```python
 glob.iglob('src/../**/likwid.so*', recursive=True)
```

Moreover, they are some bugs:
### use case 1:
while looping through PATH dir one raise an exception `Permission denied` what happen ?
the current implementation will use this path as `sout` it is not empty ...
### use case 2:
`likwid `is not installed, what could happen?
the last directory in PATH will be returned

**Note:** before to loop over the PATH maybe you could check if an env var such as `LIKWID_PREFIX` exists

**Comment by TomTheBear** [comment]
So, CI is working again. For use case 2 I added a sys.exit(1) after printing a message. For the first use case I didn't add something because it's rare that you have folders in PATH where you don't have access to. The CI problem was mainly that Python 3.4 does not support the recursive keyword for iglob().

Thanks again
